# Generated by Django 4.2.11 on 2024-05-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='textPost_en_us',
            field=models.TextField(null=True, verbose_name='text post'),
        ),
        migrations.AddField(
            model_name='post',
            name='textPost_ru',
            field=models.TextField(null=True, verbose_name='text post'),
        ),
        migrations.AddField(
            model_name='post',
            name='titlePost_en_us',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='titlePost_ru',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='authorPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='author post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoryPost',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category', verbose_name='category post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dataPost',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='textPost',
            field=models.TextField(verbose_name='text post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titlePost',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
    ]
